config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get '/:city/:state' => "main#index"
  post "/" => "main#index"
  get '/reset' => "main#reset"

end

app/models/weather_lookup.rb
class WeatherLookup 
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming 

  attr_accessor :temperature, :icon, :today_text, :tonight_text, :state, :city

  validates :city, :state, presence: true

  def initialize(state,city)
  	if city == nil
    	city = "Portland"
    end
    if state == nil
    	state = "OR"
    end
    conditions_hash = fetch_conditions(state,city.tr(" ", "_"))
    forecast_hash = fetch_forecast(state,city.tr(" ", "_"))
    assign_conditions(conditions_hash)
    assign_forecast(forecast_hash)
    verify_attributes
  end
  
  def fetch_conditions(state,city)
    HTTParty.get("http://api.wunderground.com/api/5f882a1b3107cc1e/conditions/q/#{state}/#{city}.json")
  	#http://api.wunderground.com/api/5f882a1b3107cc1e/conditions/q/OR/Portland.json

  end

  def fetch_forecast(state,city)
  	HTTParty.get("http://api.wunderground.com/api/5f882a1b3107cc1e/forecast/q/#{state}/#{city}.json")
  	#http://api.wunderground.com/api/5f882a1b3107cc1e/forecast/q/OR/Portland.json
  end

  def assign_conditions(conditions_hash)
    hourly_forecast_response = conditions_hash['current_observation']
    self.temperature = hourly_forecast_response['temp_f']
    self.icon = hourly_forecast_response['icon_url']
  end

  def assign_forecast(forecast_hash)
  	daily_forecast_response = forecast_hash['forecast']['txt_forecast']['forecastday']

  	# 2.times do |i|
  		self.today_text = daily_forecast_response[0]['fcttext']
  		self.tonight_text = daily_forecast_response[1]['fcttext']
  	# end
  end

  def verify_attributes
    self.temperature = "Temp unavailable"          if self.temperature.blank? 
    self.icon        = "http://cool.com/image.jpg" if self.icon.blank?
    self.state       = "OR"                        if self.state.blank?
    self.city        = "Portland"                  if self.city.blank?
  end

   def persisted?
    false
  end

  private
  # Using a private method to encapsulate the permissible parameters is just a good pattern
  # since you'll be able to reuse the same permit list between create and update. Also, you
  # can specialize this method with per-user checking of permissible attributes.
  def weather_lookup_params
    params.require(:weather_lookup).permit(:city, :state)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # require 'open-uri'
  # require 'json'
  
  def index
  	#http://api.wunderground.com/api/Your_Key/geolookup/q/37.776289,-122.395234.json
  	#@w_api = Wunderground.new("5f882a1b3107cc1e")
  	#@weather_lookup = WeatherLookup.new("OR","Portland")
  	#@weather_lookup2 = JSON.parse(open("http://api.wunderground.com/api/5f882a1b3107cc1e/conditions/q/OR/Portland.json").read)

  	@weather_lookup1 = WeatherLookup.new("OR","Portland")
    @weather_lookup2 = WeatherLookup.new(params[:state],params[:city])
    @weather_lookup3 = WeatherLookup.new(params[:state2],params[:city2])
  	@state = params[:state]
  	@city = params[:city]
    @state2 = params[:state2]
    @city2 = params[:city2]
  end

  def reset
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Portland vs...</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Ultra|Slabo+13px' %>
    <%= csrf_meta_tags %>
  </head>
<body>

<div class="container">
  <h1><%= image_tag 'bird.png', class: "pull-left", width: "70px"%> Portland vs 
    <% if @city == nil %>
      ...
    <% elsif @city2 == nil %>
      <%= @city.titleize %>
    <% else %>
      <%= @city.titleize %> vs <%= @city2.titleize %>
    <% end %>
  </h1>
  <p>Proving Portland's weather isn't always rainy and drab. Try a comparison. Or 2!</p><br clear="all"/>
  <%= yield %>
</div>

</body>
</html>

app/views/main/index.html.erb
<%#= @w_api.hourly_and_forecast_for("OR","Portland") %>

<!-- <p>It is <%#= @weather_lookup.temperature %> degrees in Portland, OR!
<%#= image_tag @weather_lookup.icon %></p>

<p>Today: <%#= @weather_lookup.today_text %></p>
<p>Tonight: <%#= @weather_lookup.tonight_text %></p> -->

<div class="row">
	<div class="col-md-2">
			<%= form_tag(root_path()) do %>
			  <% if @city == nil %>
		      <div class="form-group">
		        <%= text_field_tag :city, "", placeholder: "Enter city", class: "form-control", required: "required" %>
		      </div>
				  <div class="form-group">
				    <%= text_field_tag :state, "", placeholder: "Enter state", class: "form-control", required: "required" %>
				  </div>
				  <%= submit_tag "Compare it!", class: "btn btn-primary" %>

				<% elsif @city2 == nil %>
				  <div class="form-group">
				    <%= text_field_tag :city2, "", placeholder: "Enter city 2", class: "form-control", required: "required" %>
				  </div>
				  <div class="form-group">
				    <%= text_field_tag :state2, "", placeholder: "Enter state 2", class: "form-control", required: "required" %> 
				  </div>
				  <div style="display:none">
             		<%= text_field_tag :city, "", value: @city %>
             		<%= text_field_tag :state, "", value: @state %>
				  </div>
				  <%= submit_tag "Compare it!", class: "btn btn-primary" %> <br/><br/> <%= link_to "Reset", reset_path, class: "white" %>
				<% else %>
				   <%= link_to "Reset", reset_path, class: "white"%>
				<% end %>
		<% end %>
	</div>
	<div class="col-md-10">
		<div class="row">
			<div class="col-md-4">
				<div class="well pdx">
		      <h2><%= @weather_lookup1.city.titleize %>, <%= @weather_lookup1.state.upcase %></h2>
			    <div class="row">
			      <div class="col-xs-3">
			        <br/>
			        <%= image_tag @weather_lookup1.icon %>
			      </div>
			      <div class="col-xs-9">
				  	  <span class="small">Currently:</span>
					    <h3><%=@weather_lookup1.temperature %> &deg;F</h3>
					    <h4>Today:</h4>
					    <p> <%= @weather_lookup1.today_text %></p>
					    <h4>Tonight:</h4>
					    <p><%= @weather_lookup1.tonight_text %></p>
				    </div>
	  		  </div>  
			  </div>
			</div>
			<div class="col-md-4">
				<% if params[:city] != nil %>
				  <div class="well pdx">
				  	<h2><%= @city.titleize %>, <%= @state.upcase %></h2>
				  	<div class="row">
					  	<div class="col-xs-3">
						    <br/>
				 		    <%= image_tag @weather_lookup2.icon %>
					    </div>
					    <div class="col-xs-9">
						    <span class="small">Currently:</span>
					  	  <h3><%=@weather_lookup2.temperature %> &deg;F</h3>
					  	  <h4>Today:</h4>
						    <p> <%= @weather_lookup2.today_text %></p>
						    <h4>Tonight:</h4>
						    <p><%= @weather_lookup2.tonight_text %></p>
					    </div>
			   	  </div>
			   	</div>
			  <% end %>
			</div>
			<div class="col-md-4">
			  <% if params[:city2] != nil %>
			    <div class="well pdx">
				    <h2><%= @city2.titleize %>, <%= @state2.upcase %></h2> 
				  	<div class="row">
					    <div class="col-xs-3">
						    <br/>
				 		    <%= image_tag @weather_lookup3.icon %> 
					  	</div>
					    <div class="col-xs-9">
						    <span class="small">Currently:</span>
					  	  <h3><%=@weather_lookup3.temperature %> &deg;F</h3> 
					  	  <h4>Today:</h4>
						    <p><%= @weather_lookup3.today_text %></p> 
						    <h4>Tonight:</h4>
						    <p><%= @weather_lookup3.tonight_text %></p>
					    </div>
					  </div>
					</div>
			  <% end %>
			</div>
		</div>
	</div>
</div>

app/views/main/reset.html.erb
<h1>Reset Page</h1>